In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
# pauli operators
sigma_x = np.array([[0, 1],[1, 0]])
sigma_y = np.array([[0, -1j],[1j, 0]])
sigma_z = np.array([[1, 0],[0, -1]])

#for these pauli matrices eigenvectors are eginbases
def get_bases(matrix):
    eigenvalues, eigenvectors = la.eig(matrix)
    return eigenvectors

def is_MUB (eigenbasis1, eigenbasis2):
    return np.around(np.square(la.norm(np.matmul(eigenbasis1, eigenbasis2))), decimals=1) == 1.0/len(eigenbasis1)

def check_bases_two_matrices (matrix1, matrix2):
    bases1 = get_bases(matrix1)
    bases2 = get_bases(matrix2)
    for basis1 in bases1:
        for basis2 in bases2:
            print( "Are the basis {} and basis {} mutually unbiased :> {}\n".format(basis1, basis2, is_MUB(basis1, basis2)))


In [3]:
check_bases_two_matrices(sigma_x, sigma_y)
check_bases_two_matrices(sigma_x, sigma_z)
check_bases_two_matrices(sigma_y, sigma_z)

Are the basis [ 0.70710678 -0.70710678] and basis [-0.00000000-0.70710678j  0.70710678+0.j        ] mutually unbiased :> True

Are the basis [ 0.70710678 -0.70710678] and basis [ 0.70710678+0.j          0.00000000-0.70710678j] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [-0.00000000-0.70710678j  0.70710678+0.j        ] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [ 0.70710678+0.j          0.00000000-0.70710678j] mutually unbiased :> True

Are the basis [ 0.70710678 -0.70710678] and basis [ 1.  0.] mutually unbiased :> True

Are the basis [ 0.70710678 -0.70710678] and basis [ 0.  1.] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [ 1.  0.] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [ 0.  1.] mutually unbiased :> True

Are the basis [-0.00000000-0.70710678j  0.70710678+0.j        ] and basis [ 1.  0.] mutually unbiased :> True

Are the basis [-0.00000000-0.7071

In [47]:
k=2
x1 = np.zeros(k)
x2 = np.zeros(k)
x1[k-1]=1
x2[((k-1)+1)%k]=1
x1, x2



(array([ 0.,  1.]), array([ 1.,  0.]))

In [48]:
X = np.outer(x2.T, x1)
X

array([[ 0.,  1.],
       [ 0.,  0.]])

In [49]:
d = k-1
w = np.exp((2*180j)/d)
w

(-0.28369109148652732+0.95891572341430653j)

In [50]:
y1 = np.zeros(d)
y2 = np.zeros(d)
y1[d-1]=1
y2[d-1]=1
Z = np.outer(y2.T, y1)*w
Z

array([[-0.28369109+0.95891572j]])

In [57]:
M = np.outer(X, Z)
M, M.shape

(array([[-0.00000000+0.j        ],
        [-0.28369109+0.95891572j],
        [-0.00000000+0.j        ],
        [-0.00000000+0.j        ]]), (4, 1))

In [58]:
a = np.zeros((2,2))

In [65]:
a.diagonal(1,1)

ValueError: axis1 and axis2 cannot be the same

In [79]:
d = 3
X = np.zeros((d, d))

for idx in range (1, d):
    for jdx in range (d):
        if idx == jdx:
            X[idx][jdx] = 1


X

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [81]:
w = np.exp((2*180j)/d)
Z = np.zeros((d, d), dtype=complex)

for idx in range (d-1):
    for jdx in range (d):
        if idx == jdx:
            Z[idx][jdx] = w**idx
Z

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        ,  0.81418097+0.58061118j,  0.00000000+0.j        ],
       [ 0.00000000+0.j        ,  0.00000000+0.j        ,  0.00000000+0.j        ]])

In [82]:
M = np.dot(X,Z)
M

array([[ 0.00000000+0.j        ,  0.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        ,  0.81418097+0.58061118j,  0.00000000+0.j        ],
       [ 0.00000000+0.j        ,  0.00000000+0.j        ,  0.00000000+0.j        ]])