In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
# pauli operators
sigma_x = np.array([[0, 1],[1, 0]])
sigma_y = np.array([[0, -1j],[1j, 0]])
sigma_z = np.array([[1, 0],[0, -1]])

#for these pauli matrices eigenvectors are eginbases
def get_bases(matrix):
    eigenvalues, eigenvectors = la.eig(matrix)
    return eigenvectors

def is_MUB (eigenbasis1, eigenbasis2):
    return np.around(np.square(la.norm(np.matmul(eigenbasis1, eigenbasis2))), decimals=1) == 1.0/len(eigenbasis1)

def check_bases_two_matrices (matrix1, matrix2):
    bases1 = get_bases(matrix1)
    bases2 = get_bases(matrix2)
    for basis1 in bases1:
        for basis2 in bases2:
            print( "Are the basis {} and basis {} mutually unbiased :> {}\n".format(basis1, basis2, is_MUB(basis1, basis2)))


In [3]:
check_bases_two_matrices(sigma_x, sigma_y)
check_bases_two_matrices(sigma_x, sigma_z)
check_bases_two_matrices(sigma_y, sigma_z)

Are the basis [ 0.70710678 -0.70710678] and basis [-0.00000000-0.70710678j  0.70710678+0.j        ] mutually unbiased :> True

Are the basis [ 0.70710678 -0.70710678] and basis [ 0.70710678+0.j          0.00000000-0.70710678j] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [-0.00000000-0.70710678j  0.70710678+0.j        ] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [ 0.70710678+0.j          0.00000000-0.70710678j] mutually unbiased :> True

Are the basis [ 0.70710678 -0.70710678] and basis [ 1.  0.] mutually unbiased :> True

Are the basis [ 0.70710678 -0.70710678] and basis [ 0.  1.] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [ 1.  0.] mutually unbiased :> True

Are the basis [ 0.70710678  0.70710678] and basis [ 0.  1.] mutually unbiased :> True

Are the basis [-0.00000000-0.70710678j  0.70710678+0.j        ] and basis [ 1.  0.] mutually unbiased :> True

Are the basis [-0.00000000-0.7071

In [89]:
d = 2

X = np.zeros((d, d))
for k in range (0, d):
    x1 = np.zeros(d)
    x2 = np.zeros(d)
    x1[(k+1)%d]= 1
    x2[k] = 1
    X = np.add(X, np.outer(x1.T, x2))
X



array([[ 0.,  1.],
       [ 1.,  0.]])

In [90]:

w = np.exp((2*180j)/d)
Z = np.zeros((d, d))
for l in range (0, d):
    z1 = np.zeros(d)
    z2 = np.zeros(d)
    z1[l]= w**l
    z2[l] = 1
    Z = np.add(Z, np.outer(z1.T, z2))
Z

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:7: ComplexWarning: Casting complex values to real discards the imaginary part
  import sys


array([[ 1.        ,  0.        ],
       [ 0.        , -0.59846007]])

In [106]:
np.trace(np.inner(X, Z))

0.0

In [96]:
eigenvalues, eigenvectors = la.eig(np.kron(X, Z))
eigenvectors

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678]])

In [100]:
np.inner(eigenvectors[3],eigenvectors[1])

0.0

In [101]:
def define_M (X, Z, a, b):
	return np.kron(la.matrix_power(X,a),la.matrix_power(Z,b))

In [102]:
M = define_M(X, Z, 1,1)
M

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        , -0.        ,  0.        , -0.59846007],
       [ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.59846007,  0.        , -0.        ]])

In [108]:
eigenvalues, eigenvectors = la.eig(M)
eigenvectors

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678]])

In [114]:
np.inner(eigenvectors[3].T, eigenvectors[0])

0.0

In [7]:
# -*- coding: utf-8 -*-
'''

Author: Mohammed Abuhamad
UCFID: 5013840
Description : 
			Assignment 1: Problem 3 (Unitary error basis).

'''

import numpy as np
import numpy.linalg as la
np.set_printoptions(precision=4)


#define the matrices X and Z ∈ C^(d×d):
def define_matrices_X_Z(d):
	w = np.exp((2*180j)/d) # primitive d-th root of unity
	X = np.zeros((d, d), dtype=complex)
	Z = np.zeros((d, d), dtype=complex)
	
	#construct X ∈ C^(d×d) = ∑|k+ 1〉〈k| from 0 to d-1
	for k in range (0, d):
		x1 = np.zeros(d)
		x2 = np.zeros(d)
		x1[(k+1)%d]= 1
		x2[k] = 1
		X = np.add(X, np.outer(x1.T, x2))

	#construct Z ∈ C^(d×d) = ∑ω^l|l〉〈l|
	for l in range (0, d):
		z1 = np.zeros(d)
		z2 = np.zeros(d)
		z1[l]= w**l
		z2[l] = 1
		Z = np.add(Z, np.outer(z1.T, z2))

	return X, Z

#construct M^(a,b) ∈ C^(d^2×d^2) = X^a Z^b for a,b ∈ {0,...,d−1}
def define_M (X, Z, a, b):
	return np.kron(la.matrix_power(X,a),la.matrix_power(Z,b))

#show that M^(a,b) from orthonormal basis with respect to the trace inner product
def check_basis(M):
	#get the bases:
	eigenvalues, eigenvectors = la.eig(M)


	#check every pair (orthonormal if <v_i,v_j> = 0 when i!=j) and <v_i,v_i> = 1
	checks = 0
	for idx in range(len(eigenvectors)):
		for jdx in range(len(eigenvectors)):
			if idx == jdx:
				if np.around(np.inner(eigenvectors[idx].T, eigenvectors[jdx]), decimals = 1) == 1:
					checks +=1
				else:
					print ('basis {} and {} are not orthonormal'.format(eigenvectors[idx], eigenvectors[idx]))

			else:
				if np.around(np.inner(eigenvectors[idx].T, eigenvectors[jdx]), decimals = 1) == 0:
					checks +=1
				else:
					print ('basis {} and {} are not orthonormal'.format(eigenvectors[idx], eigenvectors[idx]))
	#if checks = len(eigenvectors)
	print('All {} vector cobinations are orthonormal'.format(checks))






In [8]:
d = 3
a = 1
b = 1

#get X and Z
X, Z = define_matrices_X_Z(d)
#get M
M = define_M (X, Z, a, b)
#check the bases of M
check_basis(M)

basis [-0.2887-0.5j -0.2887+0.5j  0.5774+0.j   0.0000+0.j   0.0000+0.j
  0.0000+0.j   0.0000-0.j  -0.0000+0.j   0.0000+0.j ] and [-0.2887-0.5j -0.2887+0.5j  0.5774+0.j   0.0000+0.j   0.0000+0.j
  0.0000+0.j   0.0000-0.j  -0.0000+0.j   0.0000+0.j ] are not orthonormal
basis [-0.2887-0.5j -0.2887+0.5j  0.5774+0.j   0.0000+0.j   0.0000+0.j
  0.0000+0.j   0.0000-0.j  -0.0000+0.j   0.0000+0.j ] and [-0.2887-0.5j -0.2887+0.5j  0.5774+0.j   0.0000+0.j   0.0000+0.j
  0.0000+0.j   0.0000-0.j  -0.0000+0.j   0.0000+0.j ] are not orthonormal
basis [  0.0000e+00 +0.0000e+00j   0.0000e+00 +0.0000e+00j
   0.0000e+00 +0.0000e+00j  -2.8868e-01 -5.0000e-01j
   5.7735e-01 +0.0000e+00j   5.7735e-01 +0.0000e+00j
  -1.3468e-17 -2.3327e-17j   2.6935e-17 -6.1630e-33j
   2.6935e-17 +3.5437e-32j] and [  0.0000e+00 +0.0000e+00j   0.0000e+00 +0.0000e+00j
   0.0000e+00 +0.0000e+00j  -2.8868e-01 -5.0000e-01j
   5.7735e-01 +0.0000e+00j   5.7735e-01 +0.0000e+00j
  -1.3468e-17 -2.3327e-17j   2.6935e-17 -6.1630e-33j
  

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:34: ComplexWarning: Casting complex values to real discards the imaginary part


In [9]:
eigenvalues, eigenvectors = la.eig(M)
eigenvectors

array([[ -2.8868e-01 -5.0000e-01j,  -2.8868e-01 +5.0000e-01j,
          5.7735e-01 +0.0000e+00j,   0.0000e+00 +0.0000e+00j,
          0.0000e+00 +0.0000e+00j,   0.0000e+00 +0.0000e+00j,
          0.0000e+00 -0.0000e+00j,  -0.0000e+00 +0.0000e+00j,
          0.0000e+00 +0.0000e+00j],
       [  0.0000e+00 +0.0000e+00j,   0.0000e+00 +0.0000e+00j,
          0.0000e+00 +0.0000e+00j,  -2.8868e-01 -5.0000e-01j,
          5.7735e-01 +0.0000e+00j,   5.7735e-01 +0.0000e+00j,
         -1.3468e-17 -2.3327e-17j,   2.6935e-17 -6.1630e-33j,
          2.6935e-17 +3.5437e-32j],
       [  0.0000e+00 +0.0000e+00j,   0.0000e+00 +0.0000e+00j,
          0.0000e+00 +0.0000e+00j,   0.0000e+00 +0.0000e+00j,
          0.0000e+00 +0.0000e+00j,   0.0000e+00 +0.0000e+00j,
         -2.8868e-01 +5.0000e-01j,  -2.8868e-01 +5.0000e-01j,
          5.7735e-01 +0.0000e+00j],
       [ -2.8868e-01 +5.0000e-01j,  -2.8868e-01 -5.0000e-01j,
          5.7735e-01 +4.3141e-32j,   0.0000e+00 +0.0000e+00j,
          0.0000e+00 +0.

In [17]:
np.around(np.inner(eigenvectors[4], eigenvectors[4]), decimals = 1)

(-0-0.59999999999999998j)

In [26]:
for i in range (len(eigenvectors)-1):
    for j in range (i+1, len(eigenvectors)-1):
        print np.around(np.square(la.norm(np.matmul(eigenvectors[i], eigenvectors[j]))), decimals=1)

0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.3
0.0
0.0
0.3
0.0
0.0
0.3
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.3
0.0
0.0
0.0


In [ ]:
[ 0.0000+0.j   0.0000-0.j   0.0000+0.j  -0.2887-0.5j -0.2887+0.5j
 
[ 0.0000+0.j   0.0000-0.j   0.0000+0.j  -0.2887-0.5j -0.2887+0.5j
 -0.5774+0.j  -0.0000+0.j  -0.0000-0.j   0.0000+0.j ]
 -0.5774+0.j  -0.0000+0.j  -0.0000-0.j   0.0000+0.j ] 